In [1]:
print("hello")

hello


In [1]:
a=10
b=20
a+b


30

In [5]:
import numpy

In [4]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr1+1
var1=arr1*10
var1
arr1[2:4]
arr1[2:4]=[20,30]
arr1

array([ 1,  2, 20, 30,  5])

In [2]:
arr1.shape

(5,)

In [ ]:
2D array

In [32]:
arr2=np.array([[1,2,3,4],[5,2,3,1],[3,2000,1,2],[3,4,2,3]])
arr2.shape
arr2.ndim
arr2.size
arr2.dtype
arr2
arr2[-2,-3]

arr2
arr2[:,2]
arr2[1:3,1:3]=0
arr2

array([[1, 2, 3, 4],
       [5, 0, 0, 1],
       [3, 0, 0, 2],
       [3, 4, 2, 3]])

In [104]:
arr4=np.array([[1,5,6],[4,67,3],[19,23,4],[78,9,6],[2,8,4],[34,67,45],[3,56,22]])
arr4
arr4[::2]
arr4[::2]
arr4
arr4[::6,::2]=-1
arr4
arr4[0,0]=-1
arr4[0,2]=-1
arr4[-1,-3]=-1
arr4[-1,-1]=-1
arr4
arr4[[0,1,5],[1,1,1]]
arr4[[0,1,5],[2,2,2]]
arr4


array([[-1,  5, -1],
       [ 4, 67,  3],
       [19, 23,  4],
       [78,  9,  6],
       [ 2,  8,  4],
       [34, 67, 45],
       [-1, 56, -1]])

In [103]:
#Access 1 st,2nd,and 5th row and change values into 255
arr4[[0,1,4]]=255
arr4


array([[255, 255, 255],
       [255, 255, 255],
       [ 19,  23,   4],
       [ 78,   9,   6],
       [255, 255, 255],
       [ 34,  67,  45],
       [ -1,  56,  -1]])

In [121]:
arr4>50
arr4[arr4>50]
arr4%2==0
arr4[arr4%2==0]
arr4==0


array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [20]:
import numpy as np
arr=np.array([12,45,7,19,34,28,90,55,63])

#extract all elemnts greater than 30
arr[arr>30]

#extract all odd numbers
arr[arr%2!=0]

#Replace all numbers that are multiples of 5 with -1
arr[arr%5==0]=-1
arr

#count how many numbers are less than 50
arr[arr>50].size

1

In [27]:
arr=np.array([[10,25,40],[55,18,72],[91,30,64]])
#extract all numbers greater than 50
arr[arr>50]

#Replace all even numbers with 0
arr[arr%2==0]=0
arr
#find the sum of all numbers that are divisible by 5.
np.sum(arr[arr%5==0])

#extract the last column and replace all values with 100
arr[[0,1,2],[2,2,2]]=100
arr

#create a new array where all values greater than 60 are doubled
arr[arr>60]*=2
arr

array([[  0,  25, 200],
       [ 55,   0, 200],
       [182,   0, 200]])

In [11]:
import numpy as np
arr=np.array([[12,34,56],[78,90,23],[45,67,89]])
arr
#extract elements from the first and third row
arr[[0,2]]

#exrtract the second column from the array
arr[[0,1,2],[1,1,1]]

#extract specific elements:12,90,67 using advanced indexing
arr[[0,1,2],[0,1,1]]

#swap the first and last row of the array
arr[[0,2]]=arr[[2,0]]
arr
#or 
arr1=arr[[2,1,0]]
arr

array([[45, 67, 89],
       [78, 90, 23],
       [12, 34, 56]])

In [30]:
arr=np.array([[5,15,25],[35,45,55],[65,75,85]])
arr

#extract all numbers that are multiple of 5 and greater than30
arr[(arr%5==0)&(arr>30)]

#replace aall numbers less than 50 with -1
arr[arr<50]=-1
arr

# #extract the last column and replace all values with 100
arr[[0,1,2],[2,2,2]]=100
arr

#create a 

arr

array([[ -1,  -1, 100],
       [ -1,  -1, 100],
       [ 65,  75, 100]])

In [52]:
arr=np.array([[5,15,25],[35,45,55],[65,75,85]])
#sum
np.sum(arr,axis=0)
# #min
# #max
# #mean
# #median
# #std
# #var
# #argmax
# #argmin
np.min(arr)
np.max(arr)
np.mean(arr)
np.median(arr)
np.argmax(arr,axis=1)
arr
np.argmax(arr)


np.int64(8)

In [4]:
#zeros
import numpy as np
np.zeros((10,5),dtype=int)

#ones
np.ones((5,5),dtype=int)

#full
a=np.full((5,3,),7)

#full like
np.full_like(a,1)

#arrange 
b=np.arange(100,0,-1)
np.reshape(arr,(9,))


NameError: name 'arr' is not defined